/**
 * Vault Management API
 * This schema documents the endpoints available to the Vault Management API, accessible from the Bitwarden CLI using the `bw serve` command ([learn more](https://bitwarden.com/help/cli/)). If you\'re looking for the **Organization Management** API, refer instead to [this document](https://bitwarden.com/help/api/).
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Field { 
    name?: string;
    value?: string;
    type?: Field.TypeEnum;
}
export namespace Field {
    export type TypeEnum = '0' | '1' | '2' | '3';
    export const TypeEnum = {
        _0: '0' as TypeEnum,
        _1: '1' as TypeEnum,
        _2: '2' as TypeEnum,
        _3: '3' as TypeEnum
    };
}


