/**
 * Bitwarden CLI supplementary models
 * Project-maintained CLI response models missing from the official Vault Management API schema. Generate with pnpm run g:api:bwcli.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An organization returned by bw list organizations. Status and type describe the current user\'s membership.
 */
export interface Organization { 
    object: Organization.ObjectEnum;
    id: string;
    name: string;
    /**
     * Membership status: Revoked=-1, Invited=0, Accepted=1, Confirmed=2.
     */
    status: Organization.StatusEnum;
    /**
     * Membership role: Owner=0, Admin=1, User=2, Manager=3, Custom=4.
     */
    type: Organization.TypeEnum;
    enabled: boolean;
}
export namespace Organization {
    export type ObjectEnum = 'organization';
    export const ObjectEnum = {
        Organization: 'organization' as ObjectEnum
    };
    export type StatusEnum = -1 | 0 | 1 | 2;
    export const StatusEnum = {
        Revoked: -1 as StatusEnum,
        Invited: 0 as StatusEnum,
        Accepted: 1 as StatusEnum,
        Confirmed: 2 as StatusEnum
    };
    export type TypeEnum = 0 | 1 | 2 | 3 | 4;
    export const TypeEnum = {
        Owner: 0 as TypeEnum,
        Admin: 1 as TypeEnum,
        User: 2 as TypeEnum,
        Manager: 3 as TypeEnum,
        Custom: 4 as TypeEnum
    };
}


