/**
 * Vault Management API
 * This schema documents the endpoints available to the Vault Management API, accessible from the Bitwarden CLI using the `bw serve` command ([learn more](https://bitwarden.com/help/cli/)). If you\'re looking for the **Organization Management** API, refer instead to [this document](https://bitwarden.com/help/api/).
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SendText } from './sendText';


export interface SendTemplate { 
    name?: string;
    notes?: string;
    type?: SendTemplate.TypeEnum;
    text?: SendText;
    file?: string;
    maxAccessCount?: number;
    deletionDate?: string;
    expirationDate?: string;
    password?: string;
    disabled?: boolean;
    hideEmail?: boolean;
}
export namespace SendTemplate {
    export type TypeEnum = 0 | 1;
    export const TypeEnum = {
        NUMBER_0: 0 as TypeEnum,
        NUMBER_1: 1 as TypeEnum
    };
}


