/**
 * Vault Management API
 * This schema documents the endpoints available to the Vault Management API, accessible from the Bitwarden CLI using the `bw serve` command ([learn more](https://bitwarden.com/help/cli/)). If you\'re looking for the **Organization Management** API, refer instead to [this document](https://bitwarden.com/help/api/).
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Uris { 
    match?: Uris.MatchEnum;
    uri?: string;
}
export namespace Uris {
    export type MatchEnum = 0 | 1 | 2 | 3 | 4 | 5;
    export const MatchEnum = {
        NUMBER_0: 0 as MatchEnum,
        NUMBER_1: 1 as MatchEnum,
        NUMBER_2: 2 as MatchEnum,
        NUMBER_3: 3 as MatchEnum,
        NUMBER_4: 4 as MatchEnum,
        NUMBER_5: 5 as MatchEnum
    };
}


